In [1]:
!pip install -q gensim

# Embedding
Representación de una palabra con un vector

In [2]:
from gensim.models import Word2Vec
import numpy as np
from nltk.tokenize import word_tokenize
import nltk

In [3]:
nltk.download("punkt")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\daniel.martinezcarre\AppData\Roaming\nltk_dat
[nltk_data]     a...
[nltk_data]   Package punkt is already up-to-date!


True

In [4]:
text1 = "The Titanic sailed with hope and illusion to cross the Atlantic."
text2 = "The sinking of the Titanic was one of the greatest maritime tragedies."
text3 = """
En 1912, el Titanic zarpó con la esperanza y la ilusión de cruzar el Atlántico
de una manera nunca antes vista, encapsulando el espíritu optimista de una era
que creía fervientemente en el progreso humano y la tecnología.
Esa esperanza se convirtió en desesperación en cuestión de momentos cuando, en una fría noche de abril, un iceberg se interpuso en su camino.
Los sistemas de seguridad, que se consideraban a prueba de fallos,
se mostraron trágicamente inadecuados, ya que no había suficientes botes salvavidas para todos los pasajeros.
Las consecuencias fueron devastadoras: más de mil quinientas almas se sumergieron en el helado abrazo del mar, en un suceso que sirvió como un doloroso recordatorio de la vulnerabilidad humana ante las fuerzas de la naturaleza.
"""

token1 = word_tokenize(text1.lower())
token2 = word_tokenize(text2.lower())
token3 = word_tokenize(text3.lower())

model = Word2Vec([token1,token2], vector_size=10, window=5,min_count=1, sg=0)

In [5]:
model.wv["titanic"]

array([ 0.07380505, -0.01533471, -0.04536613,  0.06554051, -0.0486016 ,
       -0.01816018,  0.0287658 ,  0.00991874, -0.08285215, -0.09448818],
      dtype=float32)

In [6]:
model.wv.index_to_key

['the',
 'titanic',
 'of',
 '.',
 'to',
 'sailed',
 'with',
 'hope',
 'and',
 'illusion',
 'tragedies',
 'maritime',
 'atlantic',
 'sinking',
 'was',
 'one',
 'greatest',
 'cross']

In [7]:
model.wv.vectors

array([[-0.00533529,  0.00234108,  0.05100109,  0.09007515, -0.09300441,
        -0.07114274,  0.06462159,  0.0897437 , -0.05013351, -0.03758188],
       [ 0.07380505, -0.01533471, -0.04536613,  0.06554051, -0.0486016 ,
        -0.01816018,  0.0287658 ,  0.00991874, -0.08285215, -0.09448818],
       [ 0.07314318,  0.05068447,  0.06756418,  0.00761333,  0.06352984,
        -0.03403559, -0.00944484,  0.05769715, -0.07519794, -0.03932276],
       [-0.07511582, -0.00930042,  0.09538119, -0.07319167, -0.02333769,
        -0.01937741,  0.08077437, -0.05930896,  0.00045162, -0.04753734],
       [-0.09605531,  0.05007488, -0.08771511, -0.04397089, -0.00030261,
        -0.00293051, -0.07658089,  0.09618904,  0.04986942,  0.0924733 ],
       [-0.08149301,  0.04492383, -0.04143354,  0.00814035,  0.08508364,
        -0.04457033,  0.0452612 , -0.0678119 , -0.03539221,  0.09415707],
       [-0.01577653,  0.00321372, -0.0414063 , -0.07682689, -0.01508008,
         0.02469795, -0.00888027,  0.05533662

In [8]:
model.wv["cross"]

array([-0.037098  , -0.08745642,  0.05437467,  0.06509756, -0.0078755 ,
       -0.06709856, -0.07085925, -0.0249706 ,  0.05143254, -0.03665238],
      dtype=float32)

In [9]:
model.wv.most_similar("maritime", topn=3)

[('one', 0.7191647887229919),
 ('was', 0.5374302268028259),
 ('titanic', 0.3582616448402405)]

### Búsqueda de similitudes

In [10]:
model.wv.most_similar(positive=["the", "maritime"], negative=["and"], topn=3)

[('titanic', 0.5306490063667297),
 ('tragedies', 0.3752540647983551),
 ('one', 0.3642173409461975)]

In [11]:
model.wv.distance("the", "maritime")

0.7727770805358887

### Embeddings de párrafos
Importante para saber si 2 párrafos van sobre el mismo asunto o no.

In [12]:
# si quisiésemos hacer un embedding de un párrafo o sentencia
# podemos hacer la media de los embeddings de sus tokens
embedding1 = sum(model.wv[w] for w in token1) / len(token1)
embedding2 = sum(model.wv[w] for w in token2) / len(token2)

# para ver la distancia entre dos párrafos
from scipy.spatial import distance
cosine_dist = distance.cosine(embedding1, embedding2)
print(cosine_dist)

0.5285577476024628
