# Numpy
Biblioteca que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas.

In [3]:
import numpy as np

> Un array unidimensional es un **vector**.

In [3]:
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [9]:
x = np.array([[1, 2, 3],
               [4, 5, 6]])

x = x.astype(float) # RECOMENDABLE realizar este parseo para optimizar datos.

print(x.ndim)   # Cuenta el número de dimensiones del array.
print(x.shape)  # Muestra el número de filas y el de columnas. [RETORNA TUPLA]
print(x.dtype)  # Muestra el tipo de datos con el que se está trabajando.
print(x.size)   # Muestra el número de elementos del array.

x.shape = (3, 2) # Esto también se puede hacer con el método 'reshape': np.reshape(x, (3, 2))
print(x)

2
(2, 3)
float64
6
[[1. 2.]
 [3. 4.]
 [5. 6.]]


> Para crear una **matriz de 0s**:

In [12]:
y = np.zeros((3,2))
print(y)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


> Para crear una **matriz diagonal**:

In [13]:
y = np.eye(3)
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


> Para hacer **rangos** tienes las mismas funciones:

In [15]:
x = np.arange(2, 6, 0.5)
print(x)

[2.  2.5 3.  3.5 4.  4.5 5.  5.5]


> Para configurar el número de valores que haya en un rango:

In [16]:
x = np.linspace(2, 7, 15)   # El 15 es el número de valores que quieres que muestre del rango.
print(x)

[2.         2.35714286 2.71428571 3.07142857 3.42857143 3.78571429
 4.14285714 4.5        4.85714286 5.21428571 5.57142857 5.92857143
 6.28571429 6.64285714 7.        ]


Si no se especifica el número de valores mostrará por defecto 50 números.

### Random

> Seed (semilla) se utiliza para crear singletons y tener un valor único.

In [20]:
np.random.seed(42)
x = np.random.randint(2, 8)
print(x)

5


In [42]:
x = np.random.random(9)
x

array([0.30461377, 0.09767211, 0.68423303, 0.44015249, 0.12203823,
       0.49517691, 0.03438852, 0.9093204 , 0.25877998])

In [51]:
np.random.uniform(10, 20, size=10)

array([14.27107789, 18.18014766, 18.60730583, 10.06952131, 15.10747303,
       14.17411003, 12.2210781 , 11.19865367, 13.37615171, 19.42909704])

In [62]:
np.random.normal(10, 20, size=10)

array([31.14847018, 11.02721719, 27.44894315, 31.32397088, -9.18016193,
       37.64009208, 28.1024392 , -2.07808745, 16.0889824 , 15.14414982])

Se puede establecer un random con la probabilidad de cada elección con la 'p':

In [69]:
np.random.choice([1,2,3,4,5,6], size = 10, p=[0.5,.1,.1,.1,.1,.1])
                # VALORES       # TIRADAS   # PROBABILIDAD

array([1, 1, 1, 5, 4, 1, 1, 1, 1, 1])

In [71]:
np.nan  # No es un número

nan

> Para crear array distorsionados:

In [75]:
x = np.array([[1, 2, 3],
               [4, 5, 6]])
x[:,1:3]    # todas las filas, desde la columna 2 al 3.

array([[2, 3],
       [5, 6]])

De la fila 1 coger el 1º elemento, de la fila 2 coger el 1º elemento y de la fila 0 coger el 1º elemento.

In [4]:
x = np.array(range(9)).reshape((3,3))
print(x)
x[[1, 2, 0], [1, 1, 1]]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([4, 7, 1])

> Para sacar booleanos de determinadas condiciones, se crea un array nuevo de booleanos:

In [91]:
print(x)
print(x > 2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [5]:
b = x > 2
print(x[b])    # Para mostrar los elementos que devuelven True
n = np.bitwise_not(b)   # Para mostrar los elementos que devuelven False en la condición
print(x[n])

[3 4 5 6 7 8]
[0 1 2]


## Operaciones de broadcasting

In [9]:
print(x)
print()
print(x + 5)   # Hace un array nuevo

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


### Ejercicios

In [12]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
np.full((3,3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Para reemplazar los impares por (-1):

In [19]:
x = np.arange(10)
x[x % 2 != 0] = -1
print(x)    # En este caso machaca el mismo array

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


> **axis**: depende del número de dimensiones, por defecto es todo, 0 = x, 1 = y

In [25]:
x = np.array([[1, 2, 3],
               [4, 5, 6]])
np.sum(x, axis = 0)    # En el eje X en este caso, en caso de columnas el axis = 1.


array([5, 7, 9])

In [26]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where((b > 5) & (b < 10))

(array([0, 4, 6, 8, 9], dtype=int64),)

> Invertir las columnas 1 y 2

In [27]:
arr = np.arange(9).reshape(3,3)
arr[:, [0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

In [30]:
import random
np.random.uniform(5, 10, size=(5,3))

array([[5.3956551 , 6.53021976, 9.50335834],
       [9.55744704, 8.00778015, 8.9717496 ],
       [8.23472603, 7.53935682, 5.19472286],
       [5.46960163, 6.73751969, 9.493124  ],
       [8.72970646, 9.30576342, 7.01749509]])